spring:
  datasource:
    url: jdbc:mariadb://13.125.205.193:3306/memberDB?serverTimezone=Asia/Seoul&characterEncoding=utf8&useUnicode=true
    username: pldbid
    password: pldbpw
    driver-class-name: org.mariadb.jdbc.Driver
admin:
  property: "local"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka
  instance:
    prefer-ip-address: true